# Generated by Django 2.2.4 on 2019-08-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.AutoField(primary_key=True, serialize=False)),
                ('tags', models.CharField(max_length=100)),
                ('goods_name', models.CharField(max_length=20)),
                ('good_price', models.FloatField()),
                ('good_img_id', models.CharField(max_length=10)),
            ],
        ),
    ]
