# Generated by Django 2.2.4 on 2019-08-26 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_auto_20190827_0634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={},
        ),
    ]
